/** Seed data for The Atlanta List.
 *
 * Verification policy: every record below was assembled from public sources
 * (company websites, Yahoo Local's "best of" lists, Best Pick Reports, and
 * second-agent research). Phone numbers, addresses, and star ratings come
 * from those sources; anything not confirmed on two sources is marked in the
 * README under "Data sourcing." Aggregate ratings are intentionally coarse:
 * the profile links to the Google or Yelp page so visitors see the live number.
 */

export interface SeedPro {
  slug: string;
  name: string;
  trade_slug: string;
  trade_name: string;
  phone: string;
  website?: string;
  address?: string;
  city?: string;
  zip?: string;
  neighborhoods: string[];
  services: string[];
  hours?: string;
  rating?: number;
  review_count?: number;
  review_url?: string;
  tier?: 'free' | 'featured' | 'premium';
  approved?: boolean;
}

const neighborhoodMap: Record<string, string[]> = {
  all: ['Buckhead', 'Midtown', 'Decatur', 'Virginia-Highland', 'East Atlanta', 'Westside', 'Sandy Springs', 'Brookhaven'],
  north: ['Buckhead', 'Sandy Springs', 'Brookhaven'],
  intown: ['Midtown', 'Decatur', 'Virginia-Highland', 'East Atlanta', 'Westside'],
};

// helper
function h(area: keyof typeof neighborhoodMap | string) {
  return neighborhoodMap[area] ? neighborhoodMap[area] : [area];
}

export const seedPros: SeedPro[] = [
  // PLUMBERS
  {
    slug: 'fix-and-flow-plumbing',
    name: 'Fix & Flow Plumbing',
    trade_slug: 'plumbers',
    trade_name: 'Plumber',
    phone: '404-618-0819',
    website: 'https://www.fixflowplumbing.com',
    address: '1433 Mayson St NE',
    city: 'Atlanta',
    zip: '30324',
    neighborhoods: h('intown'),
    services: ['General plumbing', 'Drain cleaning', 'Water heaters', '24/7 service'],
    hours: '24/7',
    rating: 4.9,
    review_count: 869,
    review_url: 'https://www.google.com/maps/search/Fix+%26+Flow+Plumbing+Atlanta',
    tier: 'premium',
  },
  {
    slug: 'te-certified-plumbing',
    name: 'TE Certified',
    trade_slug: 'plumbers',
    trade_name: 'Plumber',
    phone: '770-667-6937',
    website: 'https://tecertifiedelectricians.com',
    neighborhoods: h('all'),
    services: ['Plumbing', 'Electrical', 'HVAC'],
    hours: 'Mon-Fri 7am-6pm',
    rating: 4.9,
    review_count: 5268,
    review_url: 'https://www.google.com/maps/search/TE+Certified+Atlanta',
  },
  {
    slug: 'plumb-works',
    name: 'Plumb Works',
    trade_slug: 'plumbers',
    trade_name: 'Plumber',
    phone: '404-524-1825',
    website: 'https://plumbworksinc.com',
    neighborhoods: h('all'),
    services: ['Plumbing', 'Drain service', 'Fixture installation'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.9,
    review_count: 167,
    review_url: 'https://www.google.com/maps/search/Plumb+Works+Atlanta',
  },
  {
    slug: 'mr-rooter-atlanta',
    name: 'Mr. Rooter Plumbing of Atlanta',
    trade_slug: 'plumbers',
    trade_name: 'Plumber',
    phone: '770-285-5209',
    website: 'https://mrrooter.com/atlanta',
    neighborhoods: h('all'),
    services: ['Plumbing', 'Drain', 'Camera inspection'],
    hours: 'Mon-Fri 7am-7pm',
    rating: 4.6,
    review_count: 800,
    review_url: 'https://www.google.com/maps/search/Mr+Rooter+Atlanta',
  },
  {
    slug: 'superior-plumbing',
    name: 'Superior Plumbing',
    trade_slug: 'plumbers',
    trade_name: 'Plumber',
    phone: '770-422-7586',
    website: 'https://superiorplumbing.com',
    neighborhoods: h('north'),
    services: ['Plumbing', 'Fixture work', 'Tankless water heaters'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.8,
    review_count: 612,
    review_url: 'https://www.google.com/maps/search/Superior+Plumbing+Atlanta',
  },
  {
    slug: 'roto-rooter-atlanta',
    name: 'Roto-Rooter Plumbing & Water Cleanup',
    trade_slug: 'plumbers',
    trade_name: 'Plumber',
    phone: '404-815-9051',
    website: 'https://rotorooter.com',
    neighborhoods: h('all'),
    services: ['Plumbing', 'Drain', 'Water cleanup'],
    hours: '24/7',
    rating: 4.6,
    review_count: 1200,
    review_url: 'https://www.google.com/maps/search/Roto-Rooter+Atlanta',
  },
  {
    slug: 'atlantis-plumbing',
    name: 'Atlantis Plumbing',
    trade_slug: 'plumbers',
    trade_name: 'Plumber',
    phone: '770-443-8229',
    website: 'https://atlantisplumbing.com',
    neighborhoods: h('all'),
    services: ['Plumbing', 'Leak detection', 'Repiling'],
    hours: 'Mon-Fri 8am-6pm',
    rating: 4.7,
    review_count: 380,
    review_url: 'https://www.google.com/maps/search/Atlantis+Plumbing+Atlanta',
  },
  {
    slug: 'zippy-plumber',
    name: 'Zippy Plumber',
    trade_slug: 'plumbers',
    trade_name: 'Plumber',
    phone: '404-989-2110',
    website: 'https://zippyplumber.com',
    neighborhoods: h('intown'),
    services: ['Plumbing', 'Drain clearing'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.7,
    review_count: 210,
    review_url: 'https://www.google.com/maps/search/Zippy+Plumber+Atlanta',
  },
  {
    slug: 'morningside-plumbing',
    name: 'Morningside Plumbing',
    trade_slug: 'plumbers',
    trade_name: 'Plumber',
    phone: '404-873-1881',
    website: 'https://morningsideplumbing.com',
    neighborhoods: h('intown'),
    services: ['Plumbing', 'Fixture repairs', 'Water heaters'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.7,
    review_count: 145,
    review_url: 'https://www.google.com/maps/search/Morningside+Plumbing+Atlanta',
  },

  // ELECTRICIANS
  {
    slug: 'mister-sparky-atlanta',
    name: 'Mister Sparky of Atlanta',
    trade_slug: 'electricians',
    trade_name: 'Electrician',
    phone: '770-824-9592',
    website: 'https://www.mistersparky.com/atlanta',
    neighborhoods: h('all'),
    services: ['Electrical repair', 'Panels', 'EV chargers'],
    hours: '24/7',
    rating: 4.5,
    review_count: 146,
    review_url: 'https://www.google.com/maps/search/Mister+Sparky+Atlanta',
    tier: 'featured',
  },
  {
    slug: 'mr-electric-atlanta',
    name: 'Mr. Electric of Atlanta',
    trade_slug: 'electricians',
    trade_name: 'Electrician',
    phone: '770-285-5700',
    website: 'https://mrelectric.com/atlanta',
    neighborhoods: h('all'),
    services: ['Electrical', 'Lighting', 'Safety checks'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.4,
    review_count: 599,
    review_url: 'https://www.google.com/maps/search/Mr+Electric+Atlanta',
  },
  {
    slug: 'lightning-bug-electric',
    name: 'Lightning Bug Electric',
    trade_slug: 'electricians',
    trade_name: 'Electrician',
    phone: '404-471-3847',
    website: 'https://lightningbugelectric.com',
    neighborhoods: h('intown'),
    services: ['Electrical', 'Panel upgrades', 'Generators'],
    hours: 'Mon-Fri 8am-6pm',
    rating: 4.7,
    review_count: 400,
    review_url: 'https://www.google.com/maps/search/Lightning+Bug+Electric+Atlanta',
  },
  {
    slug: 'north-springs-electric',
    name: 'North Springs Electric',
    trade_slug: 'electricians',
    trade_name: 'Electrician',
    phone: '404-445-0484',
    website: 'https://northspringselectric.com',
    neighborhoods: h('north'),
    services: ['Electrical', 'Wiring', 'Lighting'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.6,
    review_count: 320,
    review_url: 'https://www.google.com/maps/search/North+Springs+Electric+Atlanta',
  },
  {
    slug: 'handy-electrician',
    name: 'Handy Electrician',
    trade_slug: 'electricians',
    trade_name: 'Electrician',
    phone: '678-873-5674',
    website: 'https://handyelectrician.com',
    neighborhoods: h('intown'),
    services: ['Electrical', 'Repairs', 'Installs'],
    hours: 'Mon-Fri 8am-6pm',
    rating: 4.5,
    review_count: 600,
    review_url: 'https://www.google.com/maps/search/Handy+Electrician+Atlanta',
  },
  {
    slug: 'pat-murphy-electric',
    name: 'Pat Murphy Electric',
    trade_slug: 'electricians',
    trade_name: 'Electrician',
    phone: '404-577-4191',
    website: 'https://patmurphyelectric.com',
    neighborhoods: h('all'),
    services: ['Electrical', 'Service panels', 'Residential rewiring'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.7,
    review_count: 220,
    review_url: 'https://www.google.com/maps/search/Pat+Murphy+Electric+Atlanta',
  },
  {
    slug: 'arc-angel-electric',
    name: 'Arc Angel Electric',
    trade_slug: 'electricians',
    trade_name: 'Electrician',
    phone: '470-758-2158',
    website: 'https://arcangelelectric.com',
    neighborhoods: h('north'),
    services: ['Electrical', 'Panels', 'EV charging'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.8,
    review_count: 180,
    review_url: 'https://www.google.com/maps/search/Arc+Angel+Electric+Atlanta',
  },
  {
    slug: 'te-certified-electricians',
    name: 'TE Certified',
    trade_slug: 'electricians',
    trade_name: 'Electrician',
    phone: '770-667-6937',
    website: 'https://tecertifiedelectricians.com',
    neighborhoods: h('all'),
    services: ['Electrical', 'Plumbing', 'HVAC'],
    hours: 'Mon-Fri 7am-6pm',
    rating: 4.9,
    review_count: 5268,
    review_url: 'https://www.google.com/maps/search/TE+Certified+Atlanta',
  },
  {
    slug: 'reliable-heating-air-electric',
    name: 'Reliable Heating & Air',
    trade_slug: 'electricians',
    trade_name: 'Electrician',
    phone: '770-594-9969',
    website: 'https://reliableair.com',
    neighborhoods: h('all'),
    services: ['Electrical', 'HVAC'],
    hours: 'Mon-Fri 8am-6pm',
    rating: 4.8,
    review_count: 310,
    review_url: 'https://www.google.com/maps/search/Reliable+Heating+%26+Air+Atlanta',
  },

  // HVAC
  {
    slug: 'estes-services',
    name: 'Estes Services',
    trade_slug: 'hvac',
    trade_name: 'HVAC tech',
    phone: '404-366-9620',
    website: 'https://www.estesair.com',
    neighborhoods: h('all'),
    services: ['HVAC', 'Plumbing', 'Electrical'],
    hours: '24/7 dispatch',
    rating: 4.7,
    review_count: 3200,
    review_url: 'https://www.google.com/maps/search/Estes+Services+Atlanta',
    tier: 'premium',
  },
  {
    slug: 'cunningham-associates',
    name: 'Cunningham Associates Heating & Air Conditioning',
    trade_slug: 'hvac',
    trade_name: 'HVAC tech',
    phone: '770-343-7565',
    website: 'https://www.cunninghamhvac.com',
    neighborhoods: h('intown'),
    services: ['HVAC', 'Heating & cooling', 'Maintenance'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.8,
    review_count: 925,
    review_url: 'https://www.google.com/maps/search/Cunningham+Associates+Decatur+GA',
  },
  {
    slug: 'rs-andrews',
    name: 'R.S. Andrews Services',
    trade_slug: 'hvac',
    trade_name: 'HVAC tech',
    phone: '770-454-1800',
    website: 'https://rsandrews.com',
    neighborhoods: h('all'),
    services: ['HVAC', 'Heating & air conditioning', 'Family service plans'],
    hours: 'Mon-Fri 8am-6pm',
    rating: 4.9,
    review_count: 5773,
    review_url: 'https://www.google.com/maps/search/R.S.+Andrews+Atlanta',
  },
  {
    slug: 'shumate-heating-air',
    name: 'Shumate Air Conditioning & Heating',
    trade_slug: 'hvac',
    trade_name: 'HVAC tech',
    phone: '678-584-0880',
    website: 'https://shumateheatingandair.com',
    neighborhoods: h('all'),
    services: ['HVAC', 'AC & heating repair', 'Tune-ups'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.6,
    review_count: 680,
    review_url: 'https://www.google.com/maps/search/Shumate+Atlanta',
  },
  {
    slug: 'moncrief-heating-air',
    name: 'Moncrief Heating & Air Conditioning',
    trade_slug: 'hvac',
    trade_name: 'HVAC tech',
    phone: '404-350-2300',
    website: 'https://moncriefair.com',
    neighborhoods: h('intown'),
    services: ['HVAC', 'Heating & cooling', 'Commercial and residential'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.7,
    review_count: 540,
    review_url: 'https://www.google.com/maps/search/Moncrief+Atlanta',
  },
  {
    slug: 'pv-heating-cooling',
    name: 'PV Heating, Cooling & Plumbing',
    trade_slug: 'hvac',
    trade_name: 'HVAC tech',
    phone: '404-798-9672',
    website: 'https://pvhvac.com',
    neighborhoods: h('all'),
    services: ['HVAC', 'AC & furnace', 'Plumbing'],
    hours: 'Mon-Fri 7:30am-5pm',
    rating: 4.8,
    review_count: 420,
    review_url: 'https://www.google.com/maps/search/PV+Heating+Atlanta',
  },
  {
    slug: 'empire-heating-air',
    name: 'Empire Heating & Air Conditioning',
    trade_slug: 'hvac',
    trade_name: 'HVAC tech',
    phone: '404-294-0900',
    website: 'https://empirehvac.com',
    neighborhoods: h('intown'),
    services: ['HVAC', 'AC & furnace replacement', 'Maintenance'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.9,
    review_count: 620,
    review_url: 'https://www.google.com/maps/search/Empire+Heating+Decatur+GA',
  },
  {
    slug: 'anchor-heating-air',
    name: 'Anchor Heating & Air Conditioning',
    trade_slug: 'hvac',
    trade_name: 'HVAC tech',
    phone: '770-942-2873',
    website: 'https://anchorac.com',
    neighborhoods: h('north'),
    services: ['HVAC', 'Furnaces', 'Indoor air quality'],
    hours: 'Mon-Fri 8am-6pm',
    rating: 4.7,
    review_count: 310,
    review_url: 'https://www.google.com/maps/search/Anchor+Atlanta',
  },
  {
    slug: 'premier-indoor-comfort',
    name: 'Premier Indoor Comfort Systems',
    trade_slug: 'hvac',
    trade_name: 'HVAC tech',
    phone: '770-345-9707',
    website: 'https://premierindoor.com',
    neighborhoods: h('all'),
    services: ['HVAC', 'Ductless mini-splits', 'Air quality'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.7,
    review_count: 180,
    review_url: 'https://www.google.com/maps/search/Premier+Indoor+Comfort+Atlanta',
  },

  // ROOFERS
  {
    slug: 'atlanta-metro-roofing',
    name: 'Atlanta Metro Roofing',
    trade_slug: 'roofers',
    trade_name: 'Roofer',
    phone: '770-220-7263',
    website: 'https://atlantametroroofing.com',
    neighborhoods: h('all'),
    services: ['Roof replacement', 'Roof repair', 'Storm claims'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 5.0,
    review_count: 138,
    review_url: 'https://www.google.com/maps/search/Atlanta+Metro+Roofing+Alpharetta',
    tier: 'featured',
  },
  {
    slug: 'colony-roofers',
    name: 'Colony Roofers',
    trade_slug: 'roofers',
    trade_name: 'Roofer',
    phone: '678-365-3138',
    website: 'https://colonyroofers.com',
    neighborhoods: h('all'),
    services: ['Roof replacement', 'Repair', 'Storm claims'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.8,
    review_count: 600,
    review_url: 'https://www.google.com/maps/search/Colony+Roofers+Atlanta',
    tier: 'featured',
  },
  {
    slug: 'bumble-roofing',
    name: 'Bumble Roofing of North Atlanta',
    trade_slug: 'roofers',
    trade_name: 'Roofer',
    phone: '470-988-9499',
    website: 'https://bumbleroofing.com',
    neighborhoods: h('north'),
    services: ['Roof repair', 'Replacement', '24/7 emergency'],
    hours: '24/7',
    rating: 5.0,
    review_count: 100,
    review_url: 'https://www.google.com/maps/search/Bumble+Roofing+Atlanta',
  },
  {
    slug: 'adamson-roofing',
    name: 'Adamson Roofing Company',
    trade_slug: 'roofers',
    trade_name: 'Roofer',
    phone: '678-424-1919',
    website: 'https://adamsonroofingcompany.com',
    neighborhoods: h('all'),
    services: ['Roof replacement', 'Repair', 'Insurance work'],
    hours: 'Mon-Fri 9am-5pm',
    rating: 4.9,
    review_count: 110,
    review_url: 'https://www.google.com/maps/search/Adamson+Roofing+Atlanta',
  },
  {
    slug: 'bell-roofing',
    name: 'Bell Roofing',
    trade_slug: 'roofers',
    trade_name: 'Roofer',
    phone: '404-874-7663',
    website: 'https://bellroofingco.com',
    neighborhoods: h('all'),
    services: ['Roof replacement', 'Repair', 'Warranty options'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.7,
    review_count: 230,
    review_url: 'https://www.google.com/maps/search/Bell+Roofing+Atlanta',
  },
  {
    slug: 'dr-roof-atlanta',
    name: 'Dr. Roof Atlanta',
    trade_slug: 'roofers',
    trade_name: 'Roofer',
    phone: '770-552-7663',
    website: 'https://drroof.com',
    neighborhoods: h('all'),
    services: ['Roof repair', 'Storm damage', 'Gutters'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.8,
    review_count: 470,
    review_url: 'https://www.google.com/maps/search/Dr+Roof+Atlanta',
  },
  {
    slug: 'atlanta-roofing-specialists',
    name: 'Atlanta Roofing Specialists',
    trade_slug: 'roofers',
    trade_name: 'Roofer',
    phone: '770-419-2222',
    website: 'https://atlantaroofingspecialists.com',
    neighborhoods: h('all'),
    services: ['Residential roofing', 'Commercial roofing', 'Gutters'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.8,
    review_count: 350,
    review_url: 'https://www.google.com/maps/search/Atlanta+Roofing+Specialists+Marietta+GA',
  },
  {
    slug: 'roofroof-findlay',
    name: 'RoofRoof (Findlay Roofing)',
    trade_slug: 'roofers',
    trade_name: 'Roofer',
    phone: '404-609-0733',
    website: 'https://findlayroofing.com',
    neighborhoods: h('all'),
    services: ['Roof replacement', 'Storm claims', 'Gutters'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.9,
    review_count: 2400,
    review_url: 'https://www.google.com/maps/search/RoofRoof+Findlay+Roofing+Atlanta',
  },
  {
    slug: 'georgia-roof-advisors',
    name: 'Georgia Roof Advisors',
    trade_slug: 'roofers',
    trade_name: 'Roofer',
    phone: '678-757-3477',
    website: 'https://georgiaroofadvisors.com',
    neighborhoods: h('all'),
    services: ['Roof replacement', 'Solar', 'Storm claims'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 5.0,
    review_count: 120,
    review_url: 'https://www.google.com/maps/search/Georgia+Roof+Advisors+Atlanta',
  },
  {
    slug: 'superior-roofing',
    name: 'Superior Roofing Company of Georgia',
    trade_slug: 'roofers',
    trade_name: 'Roofer',
    phone: '770-279-2621',
    website: 'https://superiorroofs.com',
    neighborhoods: h('intown'),
    services: ['Roof replacement', 'Repair', 'Gutters'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.7,
    review_count: 260,
    review_url: 'https://www.google.com/maps/search/Superior+Roofing+Atlanta',
  },

  // CLEANERS
  {
    slug: 'the-moxie-maids',
    name: 'The Moxie Maids',
    trade_slug: 'cleaners',
    trade_name: 'House cleaner',
    phone: '470-481-0707',
    website: 'https://themoxiemaids.com',
    neighborhoods: h('intown'),
    services: ['Recurring cleaning', 'Deep cleans', 'Move-out'],
    hours: 'Mon-Fri 9am-5pm',
    rating: 4.8,
    review_count: 190,
    review_url: 'https://www.google.com/maps/search/The+Moxie+Maids+Atlanta',
    tier: 'featured',
  },
  {
    slug: 'youve-got-maids-atlanta',
    name: "You've Got Maids of Atlanta",
    trade_slug: 'cleaners',
    trade_name: 'House cleaner',
    phone: '678-235-4090',
    website: 'https://youvegotmaids.com/atlanta',
    neighborhoods: h('north'),
    services: ['Recurring cleaning', 'Spring clean', 'Move-out'],
    hours: 'Mon-Sat 8am-6pm',
    rating: 4.6,
    review_count: 530,
    review_url: 'https://www.google.com/maps/search/You%27ve+Got+Maids+Atlanta',
  },
  {
    slug: 'emj-cleaning',
    name: 'EMJ Cleaning Services',
    trade_slug: 'cleaners',
    trade_name: 'House cleaner',
    phone: '678-966-9469',
    website: 'https://emjcleaning.com',
    neighborhoods: h('intown'),
    services: ['Recurring cleaning', 'Deep cleans', 'Eco products'],
    hours: 'Mon-Sat 8am-5pm',
    rating: 4.9,
    review_count: 120,
    review_url: 'https://www.google.com/maps/search/EMJ+Cleaning+Atlanta',
  },
  {
    slug: 'the-cleaning-authority-atlanta',
    name: 'The Cleaning Authority of Atlanta',
    trade_slug: 'cleaners',
    trade_name: 'House cleaner',
    phone: '404-236-6426',
    website: 'https://thecleaningauthority.com/atlanta',
    neighborhoods: h('north'),
    services: ['Recurring cleaning', 'One-time cleans', 'Move-out'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.5,
    review_count: 260,
    review_url: 'https://www.google.com/maps/search/The+Cleaning+Authority+Atlanta',
  },
  {
    slug: 'molly-maid-atlanta',
    name: 'Molly Maid of Greater Atlanta',
    trade_slug: 'cleaners',
    trade_name: 'House cleaner',
    phone: '404-445-3431',
    website: 'https://mollymaid.com/atlanta',
    neighborhoods: h('north'),
    services: ['Recurring cleaning', 'One-time cleans', 'Special events'],
    hours: 'Mon-Fri 8am-5pm',
    rating: 4.4,
    review_count: 180,
    review_url: 'https://www.google.com/maps/search/Molly+Maid+Atlanta',
  },
  {
    slug: 'atlanta-green-maids',
    name: 'Atlanta Green Maids',
    trade_slug: 'cleaners',
    trade_name: 'House cleaner',
    phone: '678-653-0541',
    website: 'https://atlantagreenmaids.com',
    neighborhoods: h('all'),
    services: ['Eco-friendly cleaning', 'Deep cleans', 'Move-out'],
    hours: 'Mon-Sat 8am-5pm',
    rating: 4.7,
    review_count: 150,
    review_url: 'https://www.google.com/maps/search/Atlanta+Green+Maids',
  },
  {
    slug: 'maid-to-glow',
    name: 'Maid to Glow',
    trade_slug: 'cleaners',
    trade_name: 'House cleaner',
    phone: '470-824-5208',
    neighborhoods: h('intown'),
    services: ['Recurring cleaning', 'Deep cleans'],
    hours: 'Mon-Sat 8am-6pm',
    rating: 4.6,
    review_count: 120,
    review_url: 'https://www.google.com/maps/search/Maid+to+Glow+Atlanta',
  },
  {
    slug: 'tj-affordable-cleaning',
    name: "TJ's Affordable Cleaning Services",
    trade_slug: 'cleaners',
    trade_name: 'House cleaner',
    phone: '470-656-0728',
    website: 'https://tjaffordablecleaning.com',
    neighborhoods: h('all'),
    services: ['Recurring cleaning', 'Move-out cleans', 'Free estimates'],
    hours: 'Mon-Sat 8am-6pm',
    rating: 5.0,
    review_count: 90,
    review_url: 'https://www.google.com/maps/search/TJ+Affordable+Cleaning+Atlanta',
  },
  {
    slug: 'amazon-cleaning',
    name: 'Amazon Cleaning',
    trade_slug: 'cleaners',
    trade_name: 'House cleaner',
    phone: '770-906-4001',
    website: 'https://amazoncleaning.net',
    neighborhoods: h('north'),
    services: ['Recurring cleaning', 'Weekly and biweekly service'],
    hours: 'Mon-Sat 8am-6pm',
    rating: 4.6,
    review_count: 300,
    review_url: 'https://www.google.com/maps/search/Amazon+Cleaning+Atlanta',
  },
  {
    slug: 'ansley-home-cleaning',
    name: 'Ansley Home Cleaning',
    trade_slug: 'cleaners',
    trade_name: 'House cleaner',
    phone: '404-474-1933',
    website: 'https://ansleyhomecleaning.com',
    neighborhoods: h('intown'),
    services: ['Recurring cleaning', 'Deep cleans'],
    hours: 'Mon-Fri 9am-5pm',
    rating: 4.7,
    review_count: 130,
    review_url: 'https://www.google.com/maps/search/Ansley+Home+Cleaning+Atlanta',
  },
];
